# -*- coding: utf-8 -*-
"""python_handson_quizzes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugoBXce_ORrfjsMBtAaTQbv1PyPCIBCP
"""

#Week1 - Practice Hands on Quizzes - Python for Data Science

#Python Basics - Start

x=y=z=1

print(x+y+z)

a='Great'
b= 'Learning'
b = a
print(b)


type(b)

S= 'Great Learning'
print('substr 1',S[:5])
print('substr 2',S[:5])
print('substr 3',S[5])
print('substr 4',S[:])

l = [2,3]
lst = [1, 'Jai', 2, 3.0, l ]
print(lst)

s = int(input())
print(type(s))

#End - Python Basics - Start

#numpy quiz

import numpy as np
a = np.array([1, 10, 2, 0])
np.power(a, 2)


b = np.array([['m', 'l'], ['n', 'o']])
print(b[0,1]) # first element is for the array and second index of the


arr = np.arange(10)
np.hsplit(arr, 2)

#np.vsplit(arr, 2) it works on arrays of 2 or more dimensions

arr2 = np.arange(6)
arr1 = np.array([1,0,0,1,0])
print(arr2)
print(arr2.shape)
print(arr1.shape)
arr1 + arr2

b = np.array((['m', 'l', '1', '2'], ['n', 'o', 'p', 'q']))
print(b[1,3])

c = np.arange(0,22,6)
c[:] = 101
c

from google.colab import drive
drive.mount('/content/drive')

#From this section the code loads the CSV file



import os
file_dir = os.getcwd()+'/drive/MyDrive/adsp_laiedm/week_1_py_for_ds/week1-practice-hands-on-quizzes'

import pandas as pd
df = pd.read_csv(file_dir+'/Dateset_ODI+-+Dateset_ODI.csv')

df.info()

df.head()

#dataframe method to find the missing values in the df
df.isnull().sum()

#dataframe method to show the missing values in Margin columns
df[df['Margin'].isnull()]


#check the 50th row of the dataframe
df.iloc[[50]]

#How many matches were played in Devonport ground
#df[df['Ground'] == 'Devonport'].count()

devonport_matches = df[df['Ground'] == 'Devonport']
num_devonport_matches = len(devonport_matches)
print(num_devonport_matches)

df.head()

aussie_winners = df[df['Winner'] == 'Australia']
print(len(aussie_winners))

team2_winners = df[df['Winner'] == df['Team 2']]
print(len(team2_winners))

#Data visualization quiz

import pandas as pd

df = pd.read_csv(file_dir+'/prog_book.csv')

df.head()

#Book data set
df.describe(include='all').T

#get the unique values of the type in df data frame
df.Type.unique()

#value counts
df.Type.value_counts()

#strip plot
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(14,5))
sns.stripplot(x='Type', y='Rating', data=df, hue='Type')

#how do i change color for each Type in the strip plot

#box plot for rating
plt.figure(figsize=(14,10))
sns.boxplot(y='Rating', data=df)

#distribution plot for reviews
plt.figure(figsize=(10,5))
sns.distplot(df['Reviews'], kde=True)

#
df.describe(include='number').T

lst = ['Rating', 'Reviews', 'Number_Of_Pages', 'Price']
corr = df[lst].corr()

plt.figure(figsize = (14,10))
sns.heatmap(corr, annot = True, cmap = 'coolwarm', fmt= '.1f', xticklabels=corr.columns,
            yticklabels = corr.columns)

# Plot the heatmap
#plt.figure(figsize = (14, 10))
#sns.heatmap(corr, annot = True, cmap = 'coolwarm',
#        fmt = ".1f",
#        xticklabels = corr.columns,
#        yticklabels = corr.columns)

#Graded Quiz - Week 1 - workout section


import seaborn as sns

sns.stripplot

sns.distplot

import pandas as pd
#pd.read  - AttributeError: module 'pandas' has no attribute 'count'
#pd.count - AttributeError: module 'pandas' has no attribute 'count'

#is there any method read_excel which loads excel file from external source

#End Graded Quiz - Week 1 - workout section

