# -*- coding: utf-8 -*-
"""Practice Exercise - Looping_Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1buJxzRKL7235kHo7qGUJ4n8wIeph-Wif

# **LOOPING STATEMENTS EXERCISE**

### 1. Print -10 to -1 using for loop
"""

#range(start, stop[, step])
for i in range(-10, 0, 1):
  print(i)

"""### 2. Using while loop print numbers 1 to 10"""

i = 1
while i <= 10:
  print(i)
  i += 1

"""### 3. Using for loop print first ten even numbers"""

for i in range(0, 20, 2):
  print(i)

"""### 4. Using while loop generate the table of 5"""

i = 1
while i <= 12:
  print( 5 * i)
  i += 1

"""### 5. Using for loop generate the table of 8"""

for i in range(1, 13):
  print( 8 * i)

"""### 6. For numbers 1 to 100, if a number is divisible by 3, then print Fizz.
### If a number is divisible by 5, then print Buzz.
### If a number is divisible by 3 and 5 both, then print FizzBuzz
### If a number is neither divisible by 3 or 5, just print the number.

Hint: use range(1,101) function  to generate numbers from 1 to 100
"""

#import random
#r_val = random.randint(1, 100)

for i in range(1, 101):
  div_by_five = (i % 5 == 0)
  div_by_three = (i % 3 == 0)
  if div_by_five:
    print("Buzz")
  if div_by_three and div_by_five:
    print("FizzBuzz")
  if not div_by_five and not div_by_three:
    print(i)

"""### 7.  Using the range function find the sum of all numbers from 1 to 100.
    For the numbers in the range (1,100):1+2+3+4+5......+100 = 5050
"""

d = list()
d = 1
for i in range(2, 101):
  d += i
print(d)

"""### 8. Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 202 and 320 (both included)."""

for num in range(202, 321):
  if num % 7 == 0 and num % 5 != 0:
    print(num)

"""### 9. Python Program to count the number of vowels in a string.
st = "Data Science"

Output: No of vowels = 5
"""

num_vowels = 0
st = "Data Science"
for ch in st:
  match ch:
    case 'a' | 'e' | 'i' | 'o' | 'u':
      num_vowels += 1
print(num_vowels)

"""### 10. Print Data Science 5 times using for loop"""

for i in range(5):
  print('Data Science')