# -*- coding: utf-8 -*-
"""Practice Exercise - Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DPV4vnJBoL53u6R9XA8DqwrsLf0vpw4g

# **USER DEFINED FUNCTION AND LAMBDA FUNCTIONS EXERCISE**

### 1. Write a function to add, subtract, multiply and divide two variables

---

passed to it and print the result
"""

def perform_add_sub_multi_div(num1, num2):
  add = num1 + num2
  sub = num1 - num2
  multi = num1 * num2
  div = num1 / num2
  return add, sub, multi, div

perform_add_sub_multi_div(10, 5)

"""### 2. Write a Python function given range (1,10) both included, that gives the square of every number"""

def square(num1, num2):
   return [i**2 for i in range(num1,num2+1)]

square(1, 10)

"""### 3. Write a function to calculate simple interest

simple interest = (Principal amount * Annual Rate of interest * Time(in years))/100

Take values as follows

Principal Amount = 1000

Rate of interest = 3%

Time = 5 years
"""

def simple_interest(principal_amt, annual_rate_of_interest, time):
  return (principal_amt * annual_rate_of_interest * time)/100

simple_interest(1000, 3, 5)

"""### 4. Write a function to check the number is divisible by 25. The function should return True if divisible and "Not divisible" if not"""

def number_divisible_by_25(num):
  if num % 25 == 0:
    return True
  else:
    return "Not divisble"

number_divisible_by_25(100)

"""### 5. Define a function that takes an input, squares it, adds 5, then returns the answer"""

def square_add_five(num):
  return (num**2) + 5

square_add_five(4)

"""### 6. Using lambda function perform the following task : take an input, squares it, add 5, then return the answer"""

func = lambda num: (num**2) + 5
func(5)

"""### 7. Write a function to calculate the power of a number raised to other ($a^b$)"""

def power(num1, num2):
  return num1**num2

power(8, 3)

"""### 8. Write a function to calculate the area of a triangle

area of triangle = 1/2 * base * height
"""

def area_of_traingle(base, height):
  return (1/2) * base * height

area_of_traingle(10, 20)

"""### 9. Create a function that takes country as the input and returns "I am from *Country* "
"""

def from_country(cntry):
  return f"I am from {cntry}"

from_country("India")

"""### 10. Write a function to convert degree Celsius temperature to Fahrenheit"""

def celsius_to_farenheit(celsius):
  return 9/5 * celsius + 32

celsius_to_farenheit(37)