# -*- coding: utf-8 -*-
"""Practice_Exercise_Introduction_to_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xdhh-zgYp_cI6clCeVm1fMV-KqTbmluG

# **INTRO TO VARIABLE EXERCISE**

### 1. What will be the type of the *add* variable?
a = 10

b = 5.1

add = a + b
"""

a = 10
b = 5.1
add = a + b
type(add)

"""### 2. Is 5 == (3+2)?"""

5 == (3+2)

"""### 3. Add 33 in variable *a* and print the result

a = 3
"""

a = 3
a = a +33
print(a)

"""### 4. Convert integer variable *a* to float and check its type

a = 3
"""

a = float(a)

"""### 5. What will be 5 times *a* if the value of a is 10?"""

a = 10
print(a * 5)

"""### 6. Write a program to calculate the area of a triangle with base = 10 and height = 5

Hint : area of triangle = 1/2 * base * height
"""

base = 10
height = 5
area = 1/2 * base * height
print(area)

"""### 7. What will be the value of *z* in the following expression:

z = (v + w) * (x / y)

If

v = 10

w = 25

x = 70

y = 2
"""

v = 10

w = 25

x = 70

y = 2

z = (v + w) * (x /y)
print(z)

"""### 8. Swap values of *a* and *b*
If before swapping a = 10 and b = 5

Then after swapping a = 5 and b = 10
##### Values can not be hardcoded
"""

a = 10
b = 5
a , b = b , a
print(a,b)

"""### 9. Convert 35 degree Celsius temperature to Fahrenheit"""

# Formuale for convering Celsius to Farenheit is 9/5 * C + 32
F = 9/5 * 35 + 32
print(F)