# -*- coding: utf-8 -*-
"""Practice Exercise - Conditional_Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VpAKI7T6--KgTkYU6z8NtVwTGNG9A00S

# **CONDITIONAL STATEMENTS EXERCISE**

### 1. Check if a is equal to 10, If yes, print "Hello", else print "Good Bye"
a = 56
"""

a = 56
if a == 10:
  print("Hello")
else:
  print("Good Bye")

"""### 2. Check whether a number is even or odd
a = 2020
"""

a = 2020
if a % 2 == 0:
  print("Even")
else:
  print("Odd")

"""### 3.  Check whether the area of the rectangle is greater than the perimeter of the rectangle
length = 5
breadth = 10

Hint: Area of rectangle = length * breadth

Hint: Perimeter of rectangle = 2 * (length + breadth)
"""

length = 5
breadth = 10

area_gt_than_perimeter = True if (length * breadth) > 2 * (length + breadth) else False
print(area_gt_than_perimeter)

"""### 4. Calculate the average marks of a student in 5 subjects and give grades accordingly:
If average>90 then Grade = A

If average>80 then Grade = B

If average>70 then Grade = C

If average>60 then Grade = D

If average>50 then Grade = E

else Fail

Marks in subject 1= 72

Marks in subject 2= 85

Marks in subject 3= 96

Marks in subject 4= 42

Marks in subject 5= 95
"""

sub1 = 72
sub2 = 85
sub3 = 96
sub4 = 42
sub5 = 95

avg = (sub1 + sub2 + sub3 + sub4 + sub5) / 5

if avg > 90:
  print("Grade = A")
elif avg > 80:
  print("Grade = B")
elif avg > 70:
  print("Grade = C")
elif avg > 60:
  print("Grade = D")
elif avg > 50:
  print("Grade = E")
else:
  print("Fail")

"""###  5. Check if a triangle is equilateral, isosceles or scalene.

Hint :
1. An equilateral triangle is a triangle in which all three sides are equal.

2. A scalene triangle is a triangle that has three unequal sides.

3. An isosceles triangle is a triangle with (at least) two equal sides.

Dimensions of triangle:

side 1 = 6

side 2 = 8

side 3 = 12
"""

side1 = 6
side2 = 8
side3 = 12

if side1 == side2 == side3:
  print("Equilateral")
elif side1 == side2 or side2 == side3:
  print("Isoceles")
else:
  print("Scalene")

"""### 6. Check if the word "Data" is present in the sentence "I am a Data Scientist". If found print "It is present" else print FALSE"""

st = "I am a Data Scientist"
if "Data" in st:
  print("It is present")
else:
  print(False)

"""### 7. Write Python code to check if a number is positive or negative."""

v = -100
if v > 0:
  print("Positive")
elif v < 0:
  print("Negative")
else:
  print("Zero")

"""### 8. x = 20 and y = 30. Write a Python code to check if x is less than y."""

x = 20
y = 30
x < y

"""### 9. Based on the users age, divide them into three groups
    Group 1 : Age <18 , Minors who are not eligible to work
    Group 2 : 18 < Age < 60 , Eligible to work
    Group 3 : Age > 60, Too old to work as per govt. regulations.

### Write a Python code for the same
"""

age = 99
if age < 18:
  print("Minors who are not eligible to work")
elif age < 60:
  print("Eligible to work")
elif age > 60:
  print("Too old to work as per govt. regulations.")

"""### 10. From the age of 3 people determine the oldest person among them.
Age of first person = 25

Age of second person = 34

Age of third person = 45
"""

age1 = 25
age2 = 34
age3 = 45

max(age1, age2, age3)