# -*- coding: utf-8 -*-
"""Practice Exercise - Collection_of_variables_Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdIE3hB3e-KWnuop6GC_MtVPO_G74wCK

# **COLLECTION OF VARIABLES**

### 1. Create a list of repeated element (element 2,48 times)
"""

repeated_list = [2] * 48
print(repeated_list)

"""### 2. Print the second element of the list

list = ["apple","orange","grapes","watermelon"]
"""

lis = ["apple","orange","grapes","watermelon"]
print(lis[1])

"""### 3.  Replace the second element of the list with "strawberries"
list = ["apple","orange","grapes","watermelon"]
"""

lis = ["apple","orange","grapes","watermelon"]
lis[1] = "strawberries"
print(lis)

"""### 4. Iterate through the list and print the values"""

List1 = ['a','b','c']
for i in List1:
    print(i)

"""### 5. Write a Python code to print squares of all numbers present in a list = [1, 12, 24, 36, 11, 20,50]"""

number = [1, 12, 24, 36, 11, 20,50]
sq = 1
for i in number:
    sq = i * i
    print(sq)

"""### 6. Pop yellow color from the list below:
List=['white','red', 'blue', 'green','blue','yellow', 'black']
"""

List = ['white','red', 'blue', 'green','blue','yellow', 'black']
List.pop(5)
print(List)

"""### 7. Check length of list

list=["a","b","c","d","e"]
"""

List1 = ['a','b','c','d','e']
len(List1)

"""###  8. Create a dictionary with the following information:

brand = Audi

Model = Q2

Year = 1980
"""

car = { "brand" : "Audi","model" : "Q2", "year" : 1980}
print(car)

"""### 9. In the above dictionary change the year to 2019"""

car = { "brand" : "Audi","model" : "Q2", "year" : 1980}
car["year"] = 2019
print(car)

"""### 10. Create a set of following elements

1.0, "Hello", 55 , (6,7,8)
"""

mset={1.0, "Hello", 55, (6,7,8)}
print(mset)